### ISSUE TITLE
Stops indexing after >300k documents

### ISSUE THREAD

**Issue by richardbenson** [lbroudoux/es-amazon-s3-river#12]
Hi there,

Hoping this is just a mis config issue, but the river has just stopped indexing after 332k documents, the s3 bucket contains over 900k.

Was a clean install of elasticsearch with just this plugin and the cloud-aws plugin.

Upon starting, indexing seemed to progress well, but has stalled for days. I have tried restarting service and whole box as well as adding more servers to the cluster to see if they will help, but no progress.

Nothing in the logs that is relevant, just the odd "can not index /example.doc".

Any more information I can give that would help diagnose?

Thanks,

Richard

**Comment by lbroudoux** [comment]
This issue was never reproduced and I never header about some other similar cases ... Closing it.
