### ISSUE TITLE
Adding document metadata extracted with Tika

### ISSUE THREAD

**Issue by lbroudoux** [lbroudoux/es-amazon-s3-river#26]
Tika is used for parsing document's content before indexing is done within Elasticsearch. Tika also offers abstract APIs for extracting various metadata from parsed file depending on content-type. This metadata may be added to ES document in a specialized `metadata` field within mapping.

**Comment by andrewcstewart** [comment]
Is this also in reference to S3 tag:value metadata fields?

**Comment by lbroudoux** [comment]
Exactly !

**Comment by lbroudoux** [comment]
Now done.

**Comment by andrewcstewart** [comment]
Awesome!  Does this happen automatically or does it need to be setup in the river config?

**Comment by lbroudoux** [comment]
I put this as the default behaviour. No need to adjust config !
