### ISSUE TITLE
Adding IAM Role support for EC2 instance

### ISSUE THREAD

**Issue by gdelgado** [lbroudoux/es-amazon-s3-river#27]
Instead of using the access keys in the command does s3-river support using the "IAM Role" function? This would allow s3-river to query the bucket without embedding the access key and secret key into the web request.

Thanks..

**Comment by lbroudoux** [comment]
Hi @gdelgado,

s3-river does not support IAM Role for now. Connection to AWS is always done using `accessKey` and `secretKey`. 

As not being familiar with IAM Role, I've read http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-roles.html for an introduction. Does this match with your need ? It should be easy to add a river configuration flag to say "do not use any key pairs but just make a default authentification". What do you think ?

**Comment by gdelgado** [comment]
That's great.. That will address any security concerns about exposing the
access keys at the instance level.

Thanks..

**Comment by lennynyktyk** [comment]
:+1:

**Comment by lbroudoux** [comment]
Should be ok now. See README for instruction.

**Comment by lbroudoux** [comment]
Hi @gdelgado, 
I do not have an EC2 instance set up right now to test if everything is ok. Would you be able to rebuild plugin from source and perform a test before I release it ?

Regards,

**Comment by gdelgado** [comment]
Sure will it give a try and let you know.

**Comment by gdelgado** [comment]
It seems to be working with the IAM roles using my configuration.

**Comment by lbroudoux** [comment]
Nice! Thank you for the test!
