### ISSUE TITLE
Document size limited to 100,000 characters.

### ISSUE THREAD

**Issue by caseeker** [lbroudoux/es-amazon-s3-river#36]
Hi, thank you so much for this plugin, it's fitting my usecase perfectly.
One problem I encountered is that files only get indexed up to 100,000 characters.
Please let me know if you have any clue where this limitation is coming from, thank you again!

**Comment by caseeker** [comment]
Found the 100,000 character limit is coming from tika

http://elasticsearch-users.115913.n3.nabble.com/ES-Attachment-gt-indexed-documents-incomplete-td3744889.html

**Comment by chadsmall** [comment]
And in particular:
https://github.com/lbroudoux/es-amazon-s3-river/search?utf8=%E2%9C%93&q=parseToString

If can update 
```
507           String parsedContent = TikaHolder.tika().parseToString(
508	                        new BytesStreamInput(fileContent, false), fileMetadata);
```
to something along the lines of the fix that was done [here](https://github.com/elastic/elasticsearch-mapper-attachments/blob/master/src/main/java/org/elasticsearch/index/mapper/attachment/AttachmentMapper.java#L501) with 'indexedChars': 
```
            // Set the maximum length of strings returned by the parseToString method, -1 sets no limit
            parsedContent = tika.parseToString(StreamInput.wrap(content), metadata, indexedChars);
```

**Comment by lbroudoux** [comment]
Coming back from holidays and having some time to investigate issue...
Stay tuned!

**Comment by lbroudoux** [comment]
Should be ok now using the `index_chars_ratio` setting fields (see README for instructions)
